### ISSUE TITLE
读取节点数据的时候，出现 org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.StreamCorruptedException: invalid type code: 

### ISSUE THREAD

**Issue by beyondalbert** [adyliu/zkclient#8]
按照快速指南中的教程：

```java
zkClient.writeData("testPath", "testData".getBytes());
```

然后读取数据：

```java
byte[] data = zkClient.readData("testPath");
```

出现的错误：
```java
org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.StreamCorruptedException: invalid type code: 
```

这个具体怎么回事，找不到原因啊～

**Comment by adyliu** [comment]
贴一份代码出来看看
org.I0Itec.zkclient 这个包应该是没有的

**Comment by beyondalbert** [comment]
代码就是这么简单，已经贴在上面了，数据是： “14.01”
一直是抛出上面这个错误
如果数据是 “testdata”, 则出现的错误是：
org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.EOFException

感觉这个会抛出各种异常么

**Comment by adyliu** [comment]
你使用的是我这个zkclient么？还是https://github.com/sgroschupf/zkclient ?

我们这个zkclient的包名是 com.github.zkclient

**Comment by beyondalbert** [comment]
啊，不好意思啊，搞错了，那我把这个issue关了哈
